image: python:3.8

stages:
  - test

before_script:
  - pip install -r requirements.txt
  - python3 manage.py loaddata roshan/tecnews/db_test.json

test:
  stage: test
  script:
    - python manage.py roshan/tecnews/test.py
