image: python:3.8

stages:
  - build
  - test
build:
  stage: build
  before_script:
    - python3 -m venv venv/
    - source venv/bin/activate
  script:
    - pip install -r requirements.txt
    - python3 roshan/manage.py migrate
    - python3 roshan/manage.py loaddata roshan/tecnews/db_test.json
test:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - python3 roshan/manage.py test
