image: python:3.8

stages:
  - build
  - test
variables:
  VIRTUAL_ENV: venv

before_script:
  - python -m venv $VIRTUAL_ENV
  - source $VIRTUAL_ENV/bin/activate
build:
  stage: build
  script:
    - pip install -r requirements.txt
    - python3 roshan/manage.py migrate
    - python3 roshan/manage.py loaddata roshan/tecnews/db_test.json
test:
  stage: test
  script:
    - python3 roshan/manage.py test
